apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-declarative 
spec: 
  replicas: 1  # <- "명령 2"가 이미 포함됨 
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec: 
      containers: 
      - name: nginx 
        image: nginx 
        ports: 
        - containerPort: 80 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-service 
spec: 
  type: NodePort  # <- "명령 3"이 이미 포함됨 
  selector: 
    app: nginx 
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 80
